### ISSUE TITLE
Task drag-on-drop реализовать

### ISSUE THREAD

**Issue by kastrubait** [kastrubait/project-management-app#76]
## Task drag-on-drop реализовать

- [x] смена очерёдности тасок в рамках колонки
- [ ] смена принадлежности таски к колонке
- [ ] стилизация компонента при перетаскивании
- [x] адаптивная верстка
- [x] добавлен перевод и подсказки
