### ISSUE TITLE
Task add file - реализовать

### ISSUE THREAD

**Issue by kastrubait** [kastrubait/project-management-app#77]
## Task add file - реализовать

- [x] добавить загрузку файла
- выполнить рефакторинг Task component
- [x] interface DeleteTask перенести в interfaces/ITask.ts
- [x] interface DeleteTask перенести в interfaces/ITask.ts
